# Generated by Django 4.2.27 on 2025-12-23 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500)),
                ('autor', models.CharField(max_length=255)),
                ('asesor', models.CharField(max_length=255)),
                ('resumen', models.TextField()),
                ('archivo_pdf', models.FileField(upload_to='tesis_pdfs/')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('validado', 'Validado'), ('enviado', 'Enviado a ALICIA')], default='pendiente', max_length=20)),
            ],
        ),
    ]
