# Generated by Django 4.2.27 on 2026-01-20 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500, verbose_name='Título de la Tesis (dc.title)')),
                ('autor', models.CharField(max_length=255, verbose_name='Autor (dc.creator)')),
                ('autor_dni', models.CharField(help_text='Necesario para RENATI', max_length=15)),
                ('autor_orcid', models.URLField(blank=True, help_text='Opcional pero recomendado', null=True)),
                ('asesor', models.CharField(max_length=255, verbose_name='Asesor (dc.contributor.advisor)')),
                ('resumen', models.TextField(verbose_name='Resumen (dc.description.abstract)')),
                ('tipo_tesis', models.CharField(choices=[('info:eu-repo/semantics/bachelorThesis', 'Tesis de Bachiller'), ('info:eu-repo/semantics/bachelorDiploma', 'Trabajo de Suficiencia Profesional'), ('info:eu-repo/semantics/masterThesis', 'Tesis de Maestría'), ('info:eu-repo/semantics/doctoralThesis', 'Tesis Doctoral')], default='info:eu-repo/semantics/bachelorThesis', max_length=100)),
                ('ocde_codigo', models.CharField(help_text='Código OCDE (ej: 5.03.01)', max_length=20)),
                ('ocde_nombre', models.CharField(help_text='Nombre del área OCDE', max_length=200)),
                ('institucion', models.CharField(default='IESPP "13 de Julio de 1882" San Pablo', max_length=255)),
                ('archivo_pdf', models.FileField(upload_to='tesis_pdfs/')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_publicacion', models.DateField(help_text='Fecha en que se sustenta/publica')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('validado', 'Validado'), ('enviado', 'Enviado a ALICIA')], default='pendiente', max_length=20)),
                ('derechos_acceso', models.CharField(choices=[('info:eu-repo/semantics/openAccess', 'Acceso Abierto'), ('info:eu-repo/semantics/closedAccess', 'Acceso Cerrado'), ('info:eu-repo/semantics/restrictedAccess', 'Acceso Restringido')], default='info:eu-repo/semantics/openAccess', max_length=100)),
            ],
        ),
    ]
