# Generated by Django 4.2.27 on 2026-01-21 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tesis',
            options={'verbose_name': 'Investigación', 'verbose_name_plural': 'Investigaciones'},
        ),
        migrations.RemoveField(
            model_name='tesis',
            name='institucion',
        ),
        migrations.AddField(
            model_name='tesis',
            name='institucion_nombre',
            field=models.CharField(default='INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO "13 DE JULIO DE 1882"', max_length=255, verbose_name='Entidad (dc.publisher)'),
        ),
        migrations.AddField(
            model_name='tesis',
            name='institucion_pais',
            field=models.CharField(default='PE', max_length=2),
        ),
        migrations.AddField(
            model_name='tesis',
            name='institucion_ruc',
            field=models.CharField(default='20202096582', max_length=11),
        ),
        migrations.AlterField(
            model_name='tesis',
            name='archivo_pdf',
            field=models.FileField(upload_to='tesis_pdfs/', verbose_name='Documento PDF'),
        ),
        migrations.AlterField(
            model_name='tesis',
            name='autor_dni',
            field=models.CharField(help_text='Necesario para RENATI / SUNEDU', max_length=15),
        ),
        migrations.AlterField(
            model_name='tesis',
            name='autor_orcid',
            field=models.URLField(blank=True, help_text='Opcional: ID de investigador', null=True),
        ),
        migrations.AlterField(
            model_name='tesis',
            name='derechos_acceso',
            field=models.CharField(choices=[('info:eu-repo/semantics/openAccess', 'Acceso Abierto'), ('info:eu-repo/semantics/closedAccess', 'Acceso Cerrado'), ('info:eu-repo/semantics/restrictedAccess', 'Acceso Restringido')], default='info:eu-repo/semantics/openAccess', max_length=100, verbose_name='Derechos (dc.rights)'),
        ),
        migrations.AlterField(
            model_name='tesis',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de Validación'), ('validado', 'Validado por Biblioteca'), ('publicado', 'Publicado en Repositorio OAI')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='tesis',
            name='fecha_publicacion',
            field=models.DateField(blank=True, help_text='Fecha de sustentación o emisión del título', null=True),
        ),
        migrations.AlterField(
            model_name='tesis',
            name='ocde_codigo',
            field=models.CharField(help_text='Ej: 5.03.01 (Educación)', max_length=20),
        ),
        migrations.AlterField(
            model_name='tesis',
            name='ocde_nombre',
            field=models.CharField(help_text='Nombre del área (ej: Ciencias de la Educación)', max_length=200),
        ),
        migrations.AlterField(
            model_name='tesis',
            name='tipo_tesis',
            field=models.CharField(choices=[('info:eu-repo/semantics/bachelorThesis', 'Tesis de Grado de Bachiller'), ('info:eu-repo/semantics/bachelorDiploma', 'Trabajo de Suficiencia Profesional (Bachiller)'), ('info:eu-repo/semantics/bachelorThesis', 'Tesis para Título Profesional'), ('info:eu-repo/semantics/masterThesis', 'Tesis de Segunda Especialidad Profesional'), ('info:eu-repo/semantics/article', 'Informe de Práctica Pre-Profesional')], default='info:eu-repo/semantics/bachelorThesis', max_length=100, verbose_name='Tipo de Documento (dc.type)'),
        ),
        migrations.AlterField(
            model_name='tesis',
            name='titulo',
            field=models.CharField(max_length=500, verbose_name='Título de la Investigación (dc.title)'),
        ),
    ]
