# Generated by Django 4.2.27 on 2026-01-21 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigacion', '0002_alter_tesis_options_remove_tesis_institucion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tesis',
            options={'ordering': ['-fecha_registro'], 'verbose_name': 'Investigación', 'verbose_name_plural': 'Investigaciones'},
        ),
        migrations.AlterField(
            model_name='tesis',
            name='autor_dni',
            field=models.CharField(help_text='Requerido para RENATI / SUNEDU', max_length=15),
        ),
        migrations.AlterField(
            model_name='tesis',
            name='ocde_codigo',
            field=models.CharField(blank=True, help_text='Ej: 5.03.01', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tesis',
            name='ocde_nombre',
            field=models.CharField(blank=True, help_text='Nombre del área OCDE', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tesis',
            name='tipo_tesis',
            field=models.CharField(choices=[('info:eu-repo/semantics/bachelorThesis', 'Tesis de Grado de Bachiller'), ('info:eu-repo/semantics/bachelorThesis_TITULO', 'Tesis para Título Profesional'), ('info:eu-repo/semantics/bachelorDiploma', 'Trabajo de Suficiencia Profesional (Bachiller)'), ('info:eu-repo/semantics/masterThesis', 'Tesis de Segunda Especialidad Profesional'), ('info:eu-repo/semantics/article', 'Informe de Práctica Pre-Profesional')], default='info:eu-repo/semantics/bachelorThesis', max_length=100, verbose_name='Tipo de Documento (dc.type)'),
        ),
    ]
