# Generated by Django 4.2.27 on 2026-01-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigacion', '0003_alter_tesis_options_alter_tesis_autor_dni_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=255, verbose_name='Nombre Completo (dc.contributor.advisor)')),
                ('dni', models.CharField(blank=True, max_length=15, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Asesor',
                'verbose_name_plural': 'Asesores',
            },
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=255, verbose_name='Nombre Completo (dc.creator)')),
                ('dni', models.CharField(max_length=15, unique=True)),
                ('orcid', models.URLField(blank=True, help_text='ID de investigador', null=True)),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
            },
        ),
        migrations.RemoveField(
            model_name='tesis',
            name='asesor',
        ),
        migrations.RemoveField(
            model_name='tesis',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='tesis',
            name='autor_dni',
        ),
        migrations.RemoveField(
            model_name='tesis',
            name='autor_orcid',
        ),
        migrations.AddField(
            model_name='tesis',
            name='constancia_originalidad',
            field=models.FileField(blank=True, null=True, upload_to='constancias/', verbose_name='2. Constancia de Originalidad'),
        ),
        migrations.AddField(
            model_name='tesis',
            name='reporte_turnitin',
            field=models.FileField(blank=True, null=True, upload_to='turnitin/', verbose_name='3. Reporte Turnitin'),
        ),
        migrations.AlterField(
            model_name='tesis',
            name='archivo_pdf',
            field=models.FileField(upload_to='tesis_pdfs/', verbose_name='1. Documento PDF (Tesis)'),
        ),
        migrations.AddField(
            model_name='tesis',
            name='asesores',
            field=models.ManyToManyField(to='investigacion.asesor', verbose_name='Asesores (dc.contributor.advisor)'),
        ),
        migrations.AddField(
            model_name='tesis',
            name='autores',
            field=models.ManyToManyField(to='investigacion.autor', verbose_name='Autores (dc.creator)'),
        ),
    ]
