# Generated by Django 4.2.27 on 2026-07-24 00:07

import django.core.validators
from django.db import migrations, models
import investigacion.models


class Migration(migrations.Migration):
    dependencies = [
        (
            "investigacion",
            "0004_asesor_autor_remove_tesis_asesor_remove_tesis_autor_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Jurado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_completo",
                    models.CharField(max_length=255, verbose_name="Nombre completo"),
                ),
                ("orcid", models.URLField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Jurado",
                "verbose_name_plural": "Jurados",
                "ordering": ["nombre_completo"],
            },
        ),
        migrations.CreateModel(
            name="PalabraClave",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="Palabra clave"
                    ),
                ),
            ],
            options={
                "verbose_name": "Palabra clave",
                "verbose_name_plural": "Palabras clave",
                "ordering": ["nombre"],
            },
        ),
        migrations.AlterModelOptions(
            name="asesor",
            options={
                "ordering": ["nombre_completo"],
                "verbose_name": "Asesor",
                "verbose_name_plural": "Asesores",
            },
        ),
        migrations.AlterModelOptions(
            name="autor",
            options={
                "ordering": ["nombre_completo"],
                "verbose_name": "Autor",
                "verbose_name_plural": "Autores",
            },
        ),
        migrations.AddField(
            model_name="asesor",
            name="apellido_materno",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="asesor",
            name="apellido_paterno",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="asesor",
            name="nombres",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="asesor",
            name="orcid",
            field=models.URLField(
                blank=True,
                help_text="Ejemplo: https://orcid.org/0000-0000-0000-0000",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="asesor",
            name="tipo_documento",
            field=models.CharField(
                choices=[
                    ("DNI", "Documento Nacional de Identidad"),
                    ("CE", "Carné de Extranjería"),
                    ("PAS", "Pasaporte"),
                    ("OTRO", "Otro documento"),
                ],
                default="DNI",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="autor",
            name="apellido_materno",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="autor",
            name="apellido_paterno",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="autor",
            name="nombres",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="autor",
            name="tipo_documento",
            field=models.CharField(
                choices=[
                    ("DNI", "Documento Nacional de Identidad"),
                    ("CE", "Carné de Extranjería"),
                    ("PAS", "Pasaporte"),
                    ("OTRO", "Otro documento"),
                ],
                default="DNI",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="tesis",
            name="acepta_publicacion",
            field=models.BooleanField(
                default=False, verbose_name="Cuenta con autorización de publicación"
            ),
        ),
        migrations.AddField(
            model_name="tesis",
            name="autorizacion_publicacion",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="autorizaciones/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"]
                    ),
                    investigacion.models.validate_pdf_file,
                ],
                verbose_name="Autorización de publicación",
            ),
        ),
        migrations.AddField(
            model_name="tesis",
            name="checksum_sha256",
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name="tesis",
            name="disciplina_academica",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Disciplina académica"
            ),
        ),
        migrations.AddField(
            model_name="tesis",
            name="fecha_actualizacion",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="tesis",
            name="fecha_autorizacion",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tesis",
            name="fecha_disponibilidad",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de disponibilidad pública"
            ),
        ),
        migrations.AddField(
            model_name="tesis",
            name="fecha_embargo_fin",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de finalización del embargo"
            ),
        ),
        migrations.AddField(
            model_name="tesis",
            name="fecha_retiro",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tesis",
            name="formato_mime",
            field=models.CharField(
                default="application/pdf", editable=False, max_length=100
            ),
        ),
        migrations.AddField(
            model_name="tesis",
            name="grado_academico",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Grado o título obtenido"
            ),
        ),
        migrations.AddField(
            model_name="tesis",
            name="identificador_persistente",
            field=models.URLField(
                blank=True, editable=False, max_length=500, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="tesis",
            name="idioma",
            field=models.CharField(
                choices=[
                    ("spa", "Español"),
                    ("eng", "Inglés"),
                    ("que", "Quechua"),
                    ("por", "Portugués"),
                ],
                default="spa",
                max_length=10,
                verbose_name="Idioma",
            ),
        ),
        migrations.AddField(
            model_name="tesis",
            name="institucion_otorgante",
            field=models.CharField(
                blank=True,
                default='INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO "13 DE JULIO DE 1882"',
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="tesis",
            name="licencia_uri",
            field=models.URLField(
                blank=True,
                help_text="Ejemplo: https://creativecommons.org/licenses/by/4.0/",
                max_length=500,
                verbose_name="Licencia de publicación",
            ),
        ),
        migrations.AddField(
            model_name="tesis",
            name="motivo_retiro",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="tesis",
            name="numero_paginas",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tesis",
            name="pais_publicacion",
            field=models.CharField(
                default="PE", max_length=2, verbose_name="País de publicación"
            ),
        ),
        migrations.AddField(
            model_name="tesis",
            name="programa_academico",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Programa académico"
            ),
        ),
        migrations.AddField(
            model_name="tesis",
            name="retirado",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="tesis",
            name="tamano_archivo",
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="tesis",
            name="tipo_autorizacion",
            field=models.CharField(
                blank=True,
                choices=[
                    ("autor", "Autorización del autor"),
                    ("cesion", "Cesión de derechos"),
                    ("licencia", "Licencia de publicación"),
                    ("institucional", "Autorización institucional"),
                ],
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="tesis",
            name="uuid",
            field=models.UUIDField(
                blank=True, db_index=True, editable=False, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="tesis",
            name="version_publicacion",
            field=models.CharField(
                choices=[
                    ("info:eu-repo/semantics/submittedVersion", "Versión presentada"),
                    ("info:eu-repo/semantics/acceptedVersion", "Versión aceptada"),
                    ("info:eu-repo/semantics/publishedVersion", "Versión publicada"),
                ],
                default="info:eu-repo/semantics/publishedVersion",
                max_length=100,
                verbose_name="Versión de la publicación",
            ),
        ),
        migrations.AlterField(
            model_name="asesor",
            name="dni",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                unique=True,
                verbose_name="Número de documento",
            ),
        ),
        migrations.AlterField(
            model_name="asesor",
            name="nombre_completo",
            field=models.CharField(
                max_length=255, verbose_name="Nombre completo (dc.contributor.advisor)"
            ),
        ),
        migrations.AlterField(
            model_name="autor",
            name="dni",
            field=models.CharField(
                max_length=20, unique=True, verbose_name="Número de documento"
            ),
        ),
        migrations.AlterField(
            model_name="autor",
            name="nombre_completo",
            field=models.CharField(
                max_length=255, verbose_name="Nombre completo (dc.creator)"
            ),
        ),
        migrations.AlterField(
            model_name="autor",
            name="orcid",
            field=models.URLField(
                blank=True,
                help_text="Ejemplo: https://orcid.org/0000-0000-0000-0000",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="tesis",
            name="archivo_pdf",
            field=models.FileField(
                upload_to="tesis_pdfs/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"]
                    ),
                    investigacion.models.validate_pdf_file,
                ],
                verbose_name="Documento PDF de la tesis",
            ),
        ),
        migrations.AlterField(
            model_name="tesis",
            name="asesores",
            field=models.ManyToManyField(
                blank=True,
                to="investigacion.asesor",
                verbose_name="Asesores (dc.contributor.advisor)",
            ),
        ),
        migrations.AlterField(
            model_name="tesis",
            name="constancia_originalidad",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="constancias/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"]
                    ),
                    investigacion.models.validate_pdf_file,
                ],
                verbose_name="Constancia de originalidad",
            ),
        ),
        migrations.AlterField(
            model_name="tesis",
            name="derechos_acceso",
            field=models.CharField(
                choices=[
                    ("info:eu-repo/semantics/openAccess", "Acceso abierto"),
                    ("info:eu-repo/semantics/embargoedAccess", "Acceso embargado"),
                    ("info:eu-repo/semantics/restrictedAccess", "Acceso restringido"),
                    ("info:eu-repo/semantics/closedAccess", "Acceso cerrado"),
                ],
                default="info:eu-repo/semantics/openAccess",
                max_length=100,
                verbose_name="Derechos de acceso (dc.rights)",
            ),
        ),
        migrations.AlterField(
            model_name="tesis",
            name="estado",
            field=models.CharField(
                choices=[
                    ("pendiente", "Pendiente de validación"),
                    ("validado", "Validado por Biblioteca"),
                    ("publicado", "Publicado en el repositorio"),
                    ("retirado", "Retirado del repositorio"),
                ],
                db_index=True,
                default="pendiente",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="tesis",
            name="institucion_nombre",
            field=models.CharField(
                default='INSTITUTO DE EDUCACIÓN SUPERIOR PEDAGÓGICO "13 DE JULIO DE 1882"',
                max_length=255,
                verbose_name="Entidad responsable (dc.publisher)",
            ),
        ),
        migrations.AlterField(
            model_name="tesis",
            name="ocde_codigo",
            field=models.CharField(
                blank=True, help_text="Ejemplo: 5.03.01", max_length=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="tesis",
            name="reporte_turnitin",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="turnitin/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"]
                    ),
                    investigacion.models.validate_pdf_file,
                ],
                verbose_name="Reporte de Turnitin",
            ),
        ),
        migrations.AlterField(
            model_name="tesis",
            name="tipo_tesis",
            field=models.CharField(
                choices=[
                    (
                        "info:eu-repo/semantics/bachelorThesis",
                        "Tesis de grado o título profesional",
                    ),
                    (
                        "info:eu-repo/semantics/bachelorDiploma",
                        "Trabajo de suficiencia profesional",
                    ),
                    (
                        "info:eu-repo/semantics/masterThesis",
                        "Tesis de segunda especialidad o maestría",
                    ),
                    ("info:eu-repo/semantics/doctoralThesis", "Tesis doctoral"),
                    ("info:eu-repo/semantics/article", "Artículo"),
                    (
                        "info:eu-repo/semantics/researchReport",
                        "Informe de investigación",
                    ),
                ],
                default="info:eu-repo/semantics/bachelorThesis",
                max_length=100,
                verbose_name="Tipo de documento (dc.type)",
            ),
        ),
        migrations.AlterField(
            model_name="tesis",
            name="titulo",
            field=models.CharField(
                max_length=500, verbose_name="Título de la investigación (dc.title)"
            ),
        ),
        migrations.AddIndex(
            model_name="tesis",
            index=models.Index(
                fields=["estado", "fecha_publicacion"], name="tesis_estado_fecha_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tesis",
            index=models.Index(
                fields=["fecha_actualizacion"], name="tesis_actualiza_idx"
            ),
        ),
        migrations.AddField(
            model_name="tesis",
            name="jurados",
            field=models.ManyToManyField(
                blank=True, to="investigacion.jurado", verbose_name="Jurados"
            ),
        ),
        migrations.AddField(
            model_name="tesis",
            name="palabras_clave",
            field=models.ManyToManyField(
                blank=True,
                to="investigacion.palabraclave",
                verbose_name="Palabras clave (dc.subject)",
            ),
        ),
    ]
