# Generated by Django 4.2.27 on 2026-09-30 02:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("investigacion", "0005_jurado_palabraclave_alter_asesor_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tesis",
            name="institucion_nombre",
            field=models.CharField(
                default='ESCUELA DE EDUCACIÓN SUPERIOR PEDAGÓGICA PÚBLICA "13 DE JULIO DE 1882"',
                max_length=255,
                verbose_name="Entidad responsable (dc.publisher)",
            ),
        ),
        migrations.AlterField(
            model_name="tesis",
            name="institucion_otorgante",
            field=models.CharField(
                blank=True,
                default='ESCUELA DE EDUCACIÓN SUPERIOR PEDAGÓGICA PÚBLICA "13 DE JULIO DE 1882"',
                max_length=255,
            ),
        ),
    ]
