# Generated by Django 4.2.27 on 2026-08-17 03:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalisisOriginalidad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_fuente', models.CharField(db_index=True, help_text='ID de la Tesis o documento analizado', max_length=100)),
                ('titulo_documento', models.CharField(blank=True, default='', max_length=500)),
                ('texto_extraido', models.TextField(blank=True, default='')),
                ('total_palabras', models.IntegerField(default=0)),
                ('porcentaje_similitud', models.FloatField(default=0.0)),
                ('nivel_similitud', models.CharField(choices=[('bajo', 'Bajo (< 15%)'), ('moderado', 'Moderado (15% - 29%)'), ('alto', 'Alto (>= 30%)')], default='bajo', max_length=10)),
                ('score_ia', models.FloatField(default=0.0)),
                ('nivel_ia', models.CharField(choices=[('bajo', 'Bajo (< 15%)'), ('moderado', 'Moderado (15% - 29%)'), ('alto', 'Alto (>= 30%)')], default='bajo', max_length=10)),
                ('perplejidad_promedio', models.FloatField(blank=True, null=True)),
                ('burstiness_score', models.FloatField(blank=True, null=True)),
                ('excluir_citas', models.BooleanField(default=True)),
                ('min_palabras_coincidencia', models.IntegerField(default=15)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'En Procesamiento'), ('completado', 'Completado'), ('error', 'Error')], default='pendiente', max_length=20)),
                ('mensaje_error', models.TextField(blank=True, default='')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Análisis de Originalidad',
                'verbose_name_plural': 'Análisis de Originalidad',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ExclusionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excluir_citas_textuales', models.BooleanField(default=True, help_text='Excluir texto entre comillas dobles o latinas')),
                ('min_palabras_coincidencia', models.IntegerField(default=15, help_text='Ignorar bloques coincidentes de menos de N palabras')),
                ('excluir_bibliografia', models.BooleanField(default=False, help_text='Intentar detectar y omitir la sección de Referencias/Bibliografía')),
            ],
            options={
                'verbose_name': 'Configuración de Exclusión',
                'verbose_name_plural': 'Configuraciones de Exclusión',
            },
        ),
        migrations.CreateModel(
            name='DocumentFingerprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_value', models.BigIntegerField(db_index=True, help_text='Hash BLAKE2b de 64 bits del shingle')),
                ('tipo_fuente', models.CharField(choices=[('tesis_interna', 'Tesis Interna (ISP13)'), ('oai_pmh', 'Repositorio Externo (OAI-PMH)'), ('web', 'Búsqueda Web')], db_index=True, max_length=20)),
                ('id_fuente', models.CharField(db_index=True, help_text='ID primario de la tesis interna o URI de la fuente externa', max_length=100)),
                ('posicion_shingle', models.IntegerField(help_text='Posición del shingle dentro del texto original')),
            ],
            options={
                'verbose_name': 'Huella Digital de Documento',
                'verbose_name_plural': 'Huellas Digitales de Documentos',
                'indexes': [models.Index(fields=['hash_value', 'tipo_fuente'], name='originalida_hash_va_5c17cd_idx'), models.Index(fields=['tipo_fuente', 'id_fuente'], name='originalida_tipo_fu_b5b9cf_idx')],
            },
        ),
        migrations.CreateModel(
            name='CoincidenciaSimilitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_fuente_coincidente', models.CharField(choices=[('tesis_interna', 'Tesis Interna (ISP13)'), ('oai_pmh', 'Repositorio Externo (OAI-PMH)'), ('web', 'Búsqueda Web')], max_length=20)),
                ('id_fuente_coincidente', models.CharField(max_length=255)),
                ('titulo_fuente', models.CharField(blank=True, default='', max_length=500)),
                ('url_fuente', models.URLField(blank=True, default='', max_length=1000)),
                ('inicio_texto', models.IntegerField()),
                ('fin_texto', models.IntegerField()),
                ('texto_coincidente', models.TextField()),
                ('porcentaje_coincidencia_especifica', models.FloatField(default=0.0)),
                ('analisis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coincidencias', to='originalidad.analisisoriginalidad')),
            ],
            options={
                'verbose_name': 'Coincidencia de Similitud',
                'verbose_name_plural': 'Coincidencias de Similitud',
                'ordering': ['inicio_texto'],
            },
        ),
    ]
