# Generated by Django 4.2.27 on 2026-09-16 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComunicadoModal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Comunicado Oficial', max_length=200, verbose_name='Título')),
                ('subtitulo', models.CharField(blank=True, default='IESPP "13 de Julio de 1882"', max_length=200, verbose_name='Subtítulo')),
                ('imagen', models.ImageField(help_text='Se muestra en el modal que aparece al entrar a la página de inicio.', upload_to='comunicados/', verbose_name='Imagen')),
                ('texto_pie', models.CharField(blank=True, default='Información 2026', max_length=100, verbose_name='Texto del pie')),
                ('activo', models.BooleanField(default=True, help_text='Solo se muestra en el inicio si está activo. Si hay varios activos, se usa el más reciente.', verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Comunicado del modal de inicio',
                'verbose_name_plural': 'Comunicados del modal de inicio',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
