# Generated by Django 4.2.27 on 2026-09-16 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuPrincipal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('tipo', models.CharField(choices=[('enlace', 'Enlace directo'), ('menu', 'Menú desplegable')], default='menu', max_length=10, verbose_name='Tipo')),
                ('url', models.CharField(blank=True, help_text="Solo para 'Enlace directo'. Puede ser una ruta interna (ej. /repositorios/) o una URL externa completa.", max_length=300, verbose_name='URL')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Menú principal (navbar)',
                'verbose_name_plural': 'Menú principal (navbar)',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(blank=True, help_text='Título de la columna dentro del desplegable (opcional). Los ítems con el mismo texto de grupo quedan agrupados juntos.', max_length=100, verbose_name='Grupo / columna')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título')),
                ('subtitulo', models.CharField(blank=True, max_length=200, verbose_name='Subtítulo')),
                ('icono', models.CharField(default='file-alt', help_text='Nombre del ícono de Font Awesome, sin el prefijo "fas fa-" (ej. "crosshairs", "landmark"). Ver iconos en fontawesome.com/icons.', max_length=50, verbose_name='Ícono')),
                ('tipo_destino', models.CharField(choices=[('modal', 'Contenido interno (modal)'), ('url', 'Enlace / URL')], default='modal', max_length=10, verbose_name='Tipo de destino')),
                ('modal_slug', models.SlugField(blank=True, help_text='Coincide con el nombre de la plantilla en templates/modals/<slug>.html.', max_length=100, verbose_name='Slug del modal')),
                ('url', models.CharField(blank=True, max_length=300, verbose_name='URL')),
                ('destacado', models.BooleanField(default=False, help_text='Se muestra como botón grande de llamada a la acción, al final de su grupo.', verbose_name='Destacado')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.menuprincipal', verbose_name='Menú')),
            ],
            options={
                'verbose_name': 'Ítem de menú',
                'verbose_name_plural': 'Ítems de menú',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
