# Generated by Django 4.2.27 on 2026-09-17 00:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_menuprincipal_menuitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoGestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="Debe coincidir exactamente con el ítem de menú que abre este documento (ej. 'doc_reglamento', 'doc_pci', 'doc_mapro').", unique=True, verbose_name='Identificador')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('subtitulo', models.CharField(blank=True, help_text="Ej. 'Vigencia 2023 - 2028'.", max_length=200, verbose_name='Subtítulo')),
                ('archivo', models.FileField(upload_to='documentos/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Archivo PDF')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Documento de gestión (PDF)',
                'verbose_name_plural': 'Documentos de gestión (PDF)',
                'ordering': ['titulo'],
            },
        ),
    ]
