# Generated by Django 4.2.27 on 2026-09-17 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_documentogestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContenidoModal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="Debe coincidir exactamente con el modal (ej. 'mision', 'historia', 'organigrama', 'personal').", unique=True, verbose_name='Identificador')),
                ('titulo_1', models.CharField(blank=True, help_text="Ej. para 'Misión y Visión', este sería el bloque de Misión.", max_length=150, verbose_name='Título del primer bloque')),
                ('texto_1', models.TextField(blank=True, help_text='Admite HTML básico (<strong>, <em>, <p>, <br>). Se muestra tal cual, sin escapar.', verbose_name='Texto del primer bloque')),
                ('titulo_2', models.CharField(blank=True, max_length=150, verbose_name='Título del segundo bloque (opcional)')),
                ('texto_2', models.TextField(blank=True, verbose_name='Texto del segundo bloque (opcional)')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='modales/', verbose_name='Imagen (opcional)')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Contenido de modal (texto/imagen)',
                'verbose_name_plural': 'Contenidos de modales (texto/imagen)',
                'ordering': ['slug'],
            },
        ),
    ]
