# Generated by Django 4.2.27 on 2026-09-27 05:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_contenidomodal"),
    ]

    operations = [
        migrations.CreateModel(
            name="MiembroEquipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_completo",
                    models.CharField(max_length=200, verbose_name="Nombre completo"),
                ),
                (
                    "grado_academico",
                    models.CharField(
                        blank=True,
                        help_text='Opcional. Ej. "Mg.", "Dr.", "Lic.".',
                        max_length=20,
                        verbose_name="Grado académico",
                    ),
                ),
                (
                    "cargo",
                    models.CharField(
                        help_text='Ej. "Directora General", "Docente de Matemática".',
                        max_length=150,
                        verbose_name="Cargo",
                    ),
                ),
                (
                    "area",
                    models.CharField(
                        choices=[
                            ("directiva", "Directiva"),
                            ("docente", "Docente"),
                            ("administrativo", "Administrativo"),
                        ],
                        max_length=20,
                        verbose_name="Área",
                    ),
                ),
                (
                    "foto",
                    models.ImageField(
                        blank=True,
                        help_text="Si no se sube, se muestran las iniciales del nombre.",
                        null=True,
                        upload_to="equipo/",
                        verbose_name="Foto (opcional)",
                    ),
                ),
                ("orden", models.PositiveIntegerField(default=0, verbose_name="Orden")),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
            ],
            options={
                "verbose_name": "Miembro del equipo",
                "verbose_name_plural": "Miembros del equipo",
                "ordering": ["area", "orden", "nombre_completo"],
            },
        ),
    ]
