# Generated by Django 4.2.27 on 2026-09-30 02:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_miembroequipo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comunicadomodal",
            name="subtitulo",
            field=models.CharField(
                blank=True,
                default='Escuela de Educación Superior Pedagógica Pública "13 de Julio de 1882"',
                max_length=200,
                verbose_name="Subtítulo",
            ),
        ),
    ]
