# Generated by Django 4.2.27 on 2026-09-27 22:55

import biblioteca.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=120, unique=True, verbose_name="Nombre"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="Se genera a partir del nombre si se deja vacío.",
                        max_length=140,
                        unique=True,
                    ),
                ),
                (
                    "orden",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Orden"),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
            ],
            options={
                "verbose_name": "Categoría",
                "verbose_name_plural": "Categorías",
                "ordering": ["orden", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="Libro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=500, verbose_name="Título")),
                (
                    "autores",
                    models.CharField(
                        help_text="Separe varios autores con punto y coma.",
                        max_length=500,
                        verbose_name="Autores",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("libro", "Libro"),
                            ("revista", "Revista"),
                            ("manual", "Manual"),
                            ("referencia", "Obra de referencia"),
                            ("otro", "Otro"),
                        ],
                        default="libro",
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "editorial",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Editorial"
                    ),
                ),
                (
                    "anio_publicacion",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[biblioteca.models.validar_anio_publicacion],
                        verbose_name="Año de publicación",
                    ),
                ),
                (
                    "isbn",
                    models.CharField(
                        blank=True,
                        help_text="ISBN-10 o ISBN-13. Se guarda sin guiones.",
                        max_length=13,
                        validators=[biblioteca.models.validar_isbn],
                        verbose_name="ISBN",
                    ),
                ),
                (
                    "portada",
                    models.ImageField(
                        blank=True,
                        upload_to="biblioteca/portadas/",
                        verbose_name="Portada",
                    ),
                ),
                (
                    "ejemplares",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Ejemplares"
                    ),
                ),
                (
                    "ubicacion",
                    models.CharField(
                        blank=True,
                        help_text="Signatura topográfica o estante. Ej. «370.1 GAR» o «Estante B-3».",
                        max_length=50,
                        verbose_name="Ubicación",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="libros",
                        to="biblioteca.categoria",
                        verbose_name="Categoría",
                    ),
                ),
            ],
            options={
                "verbose_name": "Libro",
                "verbose_name_plural": "Libros",
                "ordering": ["-fecha_registro"],
            },
        ),
        migrations.AddConstraint(
            model_name="libro",
            constraint=models.UniqueConstraint(
                condition=models.Q(("isbn", ""), _negated=True),
                fields=("isbn",),
                name="biblioteca_libro_isbn_unico_si_no_vacio",
                violation_error_message="Ya existe un libro registrado con este ISBN.",
            ),
        ),
    ]
