# Generated by Django 4.2.27 on 2026-01-26 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Convocatoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título del Proceso')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción o Resumen')),
                ('info_correo', models.EmailField(blank=True, help_text='Correo que se mostrará al postulante para sus consultas o envío externo.', max_length=254, null=True, verbose_name='Correo Informativo')),
                ('info_mesa_partes', models.CharField(blank=True, help_text='Link o indicación de dónde debe presentarse el expediente físicamente o virtual.', max_length=500, null=True, verbose_name='Información Mesa de Partes')),
                ('estado', models.CharField(choices=[('REGISTRADO', 'Registrado'), ('PUBLICADO', 'Publicado'), ('EN_PROCESO', 'En Proceso'), ('FINALIZADO', 'Finalizado')], default='REGISTRADO', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Convocatoria',
                'verbose_name_plural': 'Convocatorias',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoConvocatoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase', models.CharField(choices=[('NORMATIVIDAD', '1. Normatividad'), ('CONVOCATORIA', '2. Convocatoria'), ('EVALUACION', '3. Evaluación de Expediente'), ('RESULTADOS', '4. Resultados Finales')], max_length=50)),
                ('nombre_documento', models.CharField(help_text='Ej: Bases de la Convocatoria, Resultados Preliminares, etc.', max_length=255, verbose_name='Nombre del Archivo')),
                ('archivo', models.FileField(upload_to='convocatorias/%Y/%m/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('convocatoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='convocatorias.convocatoria')),
            ],
        ),
    ]
