# Generated by Django 4.2.27 on 2026-01-26 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='convocatoria',
            name='mensaje_evaluacion',
            field=models.TextField(blank=True, help_text='Texto que aparecerá durante el proceso de evaluación de expedientes.', verbose_name='Mensaje Informativo de Evaluación'),
        ),
        migrations.AlterField(
            model_name='convocatoria',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción General'),
        ),
        migrations.AlterField(
            model_name='convocatoria',
            name='info_correo',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo para Consultas'),
        ),
        migrations.AlterField(
            model_name='convocatoria',
            name='info_mesa_partes',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Link Mesa de Partes / Dirección'),
        ),
        migrations.AlterField(
            model_name='documentoconvocatoria',
            name='archivo',
            field=models.FileField(upload_to='convocatorias/%Y/%m/', verbose_name='Archivo PDF'),
        ),
        migrations.AlterField(
            model_name='documentoconvocatoria',
            name='fase',
            field=models.CharField(choices=[('BASES', '1. Normatividad y Convocatoria'), ('EVALUACION', '2. Evaluación'), ('FINAL', '3. Resultados Finales')], max_length=50, verbose_name='Etapa del Documento'),
        ),
        migrations.AlterField(
            model_name='documentoconvocatoria',
            name='nombre_documento',
            field=models.CharField(max_length=255, verbose_name='Etiqueta del Archivo'),
        ),
    ]
