# Generated by Django 4.2.27 on 2026-01-26 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0002_convocatoria_mensaje_evaluacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convocatoria',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción General'),
        ),
    ]
