# Generated by Django 4.2.27 on 2026-01-08 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudIdentidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('RECUPERAR_CLAVE', 'Recuperar Clave'), ('CREAR_USUARIO', 'Crear Usuario'), ('NUEVO_CORREO', 'Nuevo Correo Office 365')], default='RECUPERAR_CLAVE', max_length=20)),
                ('dni', models.CharField(max_length=12, verbose_name='DNI del Alumno')),
                ('email_contacto', models.EmailField(max_length=254, verbose_name='Email de Contacto')),
                ('nombre_completo', models.CharField(max_length=200, verbose_name='Nombre Completo')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESADO', 'Procesado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=15)),
                ('observaciones', models.TextField(blank=True, help_text='Notas del administrador', null=True)),
            ],
            options={
                'verbose_name': 'Solicitud de Identidad',
                'verbose_name_plural': 'Solicitudes de Identidad',
            },
        ),
    ]
