# Generated by Django 4.2.27 on 2026-04-25 16:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoAdmision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('tipo_examen', models.CharField(choices=[('ordinario', 'Ordinario'), ('extraordinario', 'Extraordinario'), ('exonerado', 'Exonerado'), ('traslado_externo', 'Traslado Externo'), ('traslado_interno', 'Traslado Interno'), ('otros', 'Otros')], max_length=50, verbose_name='Tipo de examen')),
                ('fecha_examen', models.DateField(verbose_name='Fecha de examen')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('archivo', models.FileField(upload_to='admision/resultados/', verbose_name='Archivo de resultados')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('publicado', 'Publicado'), ('oculto', 'Oculto')], default='borrador', max_length=20, verbose_name='Estado')),
                ('es_destacado', models.BooleanField(default=False, verbose_name='Destacado')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('fecha_publicacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de publicación')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Resultado de admisión',
                'verbose_name_plural': 'Resultados de admisión',
                'ordering': ['orden', '-fecha_examen', '-fecha_publicacion'],
            },
        ),
    ]
