# Generated by Django 4.2.27 on 2026-04-25 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admision', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoExamenAdmision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de examen de admisión',
                'verbose_name_plural': 'Tipos de examen de admisión',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.AlterField(
            model_name='resultadoadmision',
            name='tipo_examen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resultados', to='admision.tipoexamenadmision', verbose_name='Tipo de examen'),
        ),
    ]
